### ISSUE TITLE
jumpapp fails to find Blender windows

### ISSUE THREAD

**Issue by klayman** [mkropat/jumpapp#6] opened 2015-01-17 04:49 UTC
I'm having trouble with switching to already running Blender window. Both `WM_CLASS` and `WM_NAME` are `Blender`, but I get the error `Error: found running process for 'blender', but found no window to jump to`.

**Comment by mkropat** [comment] 2015-01-17 20:44
Weird. I'm going to try installing Blender myself and see if I can reproduce.

**Comment by mkropat** [comment] 2015-01-17 20:57
I can reproduce the issue.

The reason it's not working is that Blender isn't setting the `WM_CLIENT_MACHINE` property. That property is necessary to match by PID, but it's not necessary to match by WM_CLASS. Unfortuantely there's a bug in jumpapp's logic, where it requires a WM_CLIENT_MACHINE machine to match on WM_CLASS, which again, is a bug in jumpapp.

Let me see if I can put together a fix.

**Comment by mkropat** [comment] 2015-01-17 21:17
@klayman I pushed a fix for this. It may take an hour or two for the PPA to be updated (if you've installed it that way).

I'm pretty sure it fixes the issue, but give it a try and let me know if it works.

**Comment by klayman** [comment] 2015-01-19 13:31
Yes, it works! ) Thank you very much.

**Closed** 2015-01-19 13:32 UTC
Labels: bug
