### ISSUE TITLE
intellij

### ISSUE THREAD

**Issue by shaun-sweet** [mkropat/jumpapp#30] opened 2018-02-01 18:17 UTC
Any thoughts on how to get this going with something like intellij?  It is launched thru a shell script as its entry point.

**Comment by e3rd** [comment] 2018-02-01 18:25
you mean launching intellij OR focusing already launched intellij

You may for example use `-t` flag for focusing already created instance and launching new with command.. something like: `jumpapp -t intellij /path/to/launch/script/as/fallback`

**Comment by shaun-sweet** [comment] 2018-02-01 20:12
well both really.  I can't focus it because it starts thru the shell script and basically runs a java command.

**Comment by e3rd** [comment] 2018-02-02 11:39
And what about the paragraph I've been recommending before?

> You may for example use -t flag for focusing already created instance and launching new with command.. something like: jumpapp -t intellij /path/to/launch/script/as/fallback

Did it work? If you're confused, could you tell us here the:
1. shell script path
2. and the title of running application?

**Comment by Rublis** [comment] 2018-02-03 18:28
I'm using jumpapp for intellijIdea, for me it looks this:
"jumpapp -c jetbrains-idea intellij-idea-ultimate-edition"
I'm using linux arch and I have installed it from arch repo, so I don't know if that launcher script is made by arch, or it's made by jetbrains.

**Comment by kerneldemon** [comment] 2018-05-09 14:51
A bit late to the party, but I've been using the `-i` flag to launch another jetbrains product for years:

```
jumpapp -i phpstorm64 /opt/PhpStorm-171.4424.11/bin/phpstorm.sh
```

The same approach will work with intellij-idea:

```
jumpapp -i idea64 /path/to/idea.sh
```

**Comment by michalzubkowicz** [comment] 2019-03-11 20:12
If anyone still is searching for a solution, this works perfectly now:
jumpapp -c jetbrains-idea idea

But you must have somewhere in path launch script named "idea" (InteliJ Toolbox creates one on .local/bin)

**Comment by mkropat** [comment] 2019-06-21 02:52
This seems to be working (just confirmed it myself), so I'm going to close this issue. Thanks, everyone, for sharing helpful hints.

**Closed by mkropat** 2019-06-21 02:52 UTC
